add code coverage eval

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -24,3 +24,13 @@ jobs:
       run: make build
     - name: Test & generate code coverage
       run: make test
+    - name: Evaluate code coverage
+      run: |
+        coverage=$(go tool cover -func cover.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
+        if [[ $(bc -l <<< "$coverage > 90") -eq 1 ]]; then
+          echo "Code coverage: PASS"
+          exit 0
+        else
+          echo "Code coverage: FAIL"
+          exit 1
+        fi
